### ISSUE TITLE
Access the compiler instance from the 'serverRenderer' middleware

### ISSUE THREAD

**Issue by martin-eq** [60frames/webpack-hot-server-middleware#17]
I was wondering if it would be possible to expose a reference to the compiler in the `serverRenderer` middleware as you do with the `stats`.

I want to access a file in the outputFS of the compiler (in memory) and use it to render the HTML of the page in the Server-Side Rendering way.

Would it be possible? I would like to know what you think about this, as I think it would bring flexibility to the `serverRenderer` middleware.

**Comment by richardscarrott** [comment]
@martin-eq if I were to expose the compiler to the serverRenderer how would you then use that in production where there isn't a compiler?

Can you not just import the module directly in your serverRenderer code and let Webpack bundle it into the same output?

**Comment by martin-eq** [comment]
@richardscarrott you are right, i didn't think about the production case. I think I can setup the compiler in a separate module and import it on `serverRenderer`.

Thanks for your help.
