### ISSUE TITLE
RIchard, i gave you props throughout my various releases today

### ISSUE THREAD

**Issue by faceyspacey** [60frames/webpack-hot-server-middleware#25]
https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8

https://github.com/faceyspacey/react-universal-component

...took me a while but i finally finished and shipped everything as i wanted. looking forward to your thoughts.

**Comment by richardscarrott** [comment]
@faceyspacey awesome, great article, I'm planning on digging into your various packages in more depth once I find the time, keep up the good work!
