### ISSUE TITLE
Only create webpack.config for server, omit client

### ISSUE THREAD

**Issue by jmca** [60frames/webpack-hot-server-middleware#52]
According to the docs, it looks like I have to pass a webpack.config that consists of both "client" and "server". Is there any way to pass the server config only, and omit the client (client is not needed at this moment)?

**Comment by richardscarrott** [comment]
@jmca I can see that could be useful, I'd be happy to accept a PR supporting a single server bundle.

**Comment by roastlechon** [comment]
I just happen to run into the case that I need this. Consider me on it!

**Comment by roastlechon** [comment]
@jmca @richardscarrott please whenever possible take a look at the PR. I will take any suggestions/feedback and add it in

**Comment by jmca** [comment]
@roastlechon Awesome. I don't have any street cred on this repo so I'll leave the comments to @richardscarrott.

**Comment by richardscarrott** [comment]
@jmca @roastlechon's PR is now merged and available in 0.4.0
