### ISSUE TITLE
JavaScript heap out of memory, bundles not cleared

### ISSUE THREAD

**Issue by eirikurn** [60frames/webpack-hot-server-middleware#53]
We're seeing a lot of out-of-memory errors using this library.

I've looked at #29 and think this is another reason. After doing some heap traces I see that bundles remain in memory after every change. The nodejs `module` object has a children array, which includes every generated bundle.

This issue has been fixed upstream in require-from-string@2, so a simple dep update should fix the issue here.

**Comment by eirikurn** [comment]
Here's the relevant discussion: https://github.com/floatdrop/require-from-string/pull/9

**Comment by richardscarrott** [comment]
@eirikurn Thanks for letting me know about this, I've upgraded require-from-string to v2.0.1 -- https://github.com/60frames/webpack-hot-server-middleware/pull/55

I'll release a new version shortly.

**Comment by richardscarrott** [comment]
Bit of a delay but v0.3.2 has been released with the fix
