### ISSUE TITLE
Migrate to new hooks api for webpack@4

### ISSUE THREAD

**Issue by 7rulnik** [60frames/webpack-hot-server-middleware#61]
I will do it on this week

**Comment by richardscarrott** [comment]
@7rulnik thanks for raising this -- I've not looked into the specifics (is it just `compiler.plugin` -> `compiler.tap`?) but I'd like to support v2+ if possible?

**Comment by Industrial** [comment]
I've opened a [PR](https://github.com/60frames/webpack-hot-server-middleware/pull/64)

**Comment by Industrial** [comment]
This is in master now :-)
