### ISSUE TITLE
please remove `yarn` from dependencies

### ISSUE THREAD

**Issue by Swatinem** [60frames/webpack-hot-server-middleware#69]
Well you don’t have any `require` statement that explicitly requires yarn. So I think this is most likely a bug :-)

**Comment by phyllisstein** [comment]
Any chance of cutting a new release now that #70 is in place? I add `$PWD/node_modules/.bin` to my `PATH` and I'd love to lose the occasional warnings about version mismatches. Thanks so much!

**Comment by hulkish** [comment]
please?

**Comment by josh-stevens** [comment]
+1 to this, just noticed yarn bloating out my node_modules when I brought this in
