### ISSUE TITLE
TypeError: serverRenderer is not a function

### ISSUE THREAD

**Issue by vasivas** [60frames/webpack-hot-server-middleware#71]
> TypeError: serverRenderer is not a function
>     at /home/ivan/projects/whsm/node_modules/webpack-hot-server-middleware/src/index.js:13:5

example - https://github.com/vasivas/whsm

**Comment by QuincyHe** [comment]
Had the same issue. I think we must have the render method named exactly "serverRender" inside our server entry file, just like the example.
