### ISSUE TITLE
use webpack-hot-server-middleware with typescript

### ISSUE THREAD

**Issue by dagda1** [60frames/webpack-hot-server-middleware#81]
Do you have any advice for using with typescript.

Currently my start command looks like this:

```
PORT=3600 NODE_ENV=development nodemon --watch 'src/server/**/*' -e ts,tsx --exec '../../node_modules/.bin/ts-node' ./src/index.ts
```

But this is obviously very costly as it does a hard restart when a file changes and involves compiling the webpack files each time.

**Comment by richardscarrott** [comment]
I would recommend proxying to a custom dev-server for the SSR route(s) in development, e.g.

```
if (process.env.NODE_ENV === 'production') {
    const serverRenderer = require('../webpack/dist/server');
    app.use(serverRenderer());
} else {
    app.use(proxy('http://localhost:8080')); // Proxy to dev server which handles SSR w/ webpack-hot-server-middleware
}

app.listen(6060);
```

**Comment by richardscarrott** [comment]
@dagda1 I'm going to close this as I think the proxy solution is suitable -- feel free to continue the discussion here / reopen a new issue if you still have a problem.
