### ISSUE TITLE
React Redux store not found in context

### ISSUE THREAD

**Issue by cdoublev** [60frames/webpack-hot-server-middleware#84]
Hello,

I have an issue with the latest version of `react-redux` (v6.0.0) by using this package for SSRing in development. One of its maintainers [suggested](https://github.com/reduxjs/react-redux/issues/1121) that the issue is coming from how this package is requiring the `serverRender` chunk, ie. via `require-from-string` I presume. In my previous research, I already saw that the context was server side rendered as empty.

As I saw that you also have a React/Redux boilerplate repository, do you have any thoughts on this?

**Comment by richardscarrott** [comment]
I've got a hunch it's something to do with multiple versions of React and context -- although I'd have thought marking it as external would ensure there is just a single instance.

**Comment by cdoublev** [comment]
Thank you for the feed back. It leads me to the [right place](https://github.com/facebook/react/blob/961eb65b4ba5de6bbfb6b8a075a924c284541177/packages/react-dom/src/server/ReactPartialRenderer.js#L1078).

> The logic below for Context differs depending on PROD or DEV mode. In DEV mode, we create a separate object for Context.Consumer that acts like a proxy to Context. This proxy object adds unnecessary code in PROD so we use the old behaviour (Context.Consumer references Context) to reduce size and overhead. The separate object references context via a property called "_context", which also gives us the ability to check in DEV mode if this property exists or not and warn if it does not.

I'm still wrapping my head for what it entirely means, but in the meantime, externalizing React is a working and totally acceptable solution. Thank you a lot!

**Comment by cdoublev** [comment]
This was an error on my Webpack config. I had `mode: 'production' set for the server build, which was setting `NODE_ENV` to `production`. Thank you again! :)
