### ISSUE TITLE
Why is yarn in runtime dependencies?

### ISSUE THREAD

**Issue by vovkasm** [60frames/webpack-hot-server-middleware#86]
```sh
> npm info webpack-hot-server-middleware dependencies

{ debug: '^3.1.0',
  'require-from-string': '^2.0.1',
  'source-map-support': '^0.5.3',
  yarn: '^1.5.1' }

```

yarn do not recorded as dependency in `package.json`, but npm count it. Is published in npm registry code actually the same as in this repo?

**Comment by richardscarrott** [comment]
It was accidentally added with as a dep here https://github.com/60frames/webpack-hot-server-middleware/pull/64

Removed here https://github.com/60frames/webpack-hot-server-middleware/pull/70

And published today, here https://www.npmjs.com/package/webpack-hot-server-middleware/v/0.6.0
