### ISSUE TITLE
bug flow type

### ISSUE THREAD

**Issue by maystrenkoYurii** [60frames/webpack-hot-server-middleware#91]
only windows bug flow check
![Снимок](https://user-images.githubusercontent.com/23016311/81740591-e1fa1880-94a5-11ea-89fc-bfec8c5cf81f.PNG)
fixed chenged full filename in main
![Снимок](https://user-images.githubusercontent.com/23016311/81740659-fd652380-94a5-11ea-8c04-f274acfa99ed.PNG)

**Comment by richardscarrott** [comment]
So change `"main": "src/"` -> `"main": "src/index.js"`?... I don't think the former is necessarily invalid but feel free to send a PR and I will merge.

**Comment by maystrenkoYurii** [comment]
@richardscarrott ok i am created pull reguest

**Comment by maystrenkoYurii** [comment]
@richardscarrott  Hi i opened pull request, review please

**Comment by ease-space** [comment]
fixed and merget into master
